### ISSUE TITLE
Load json when including a twig template

### ISSUE THREAD

**Issue by lewisnyman** [pattern-lab/patternengine-php-twig#11]
When you include a pattern like this:
`{% include "molecules-button" %}`

It does not load the related button.json. Currently it's fairly easy to work around by doing this:
```
{% include "molecules-button"
  with {
    "element": "a",
    "text": "Button"
  }
%}
```
But it adds a lot of duplication.

Here's an example gist of all three files: https://gist.github.com/lewisnyman/96c3fdbcb5d0fcc1c2ae

**Comment by dmolsen** [comment]
@lewisnyman -

Pattern-defined `.json` isn't checked for when a pattern is included in other patterns. If you want default data for a pattern it needs to go into `source/_data/` instead. You can put as many YAML or JSON files you want in there.

PL2 knows a bit more about patterns than PL1 did so maybe I'll revisit the decision about how to handle inheritance at some point.

PS - I apologize for taking so long to follow-up.
