### ISSUE TITLE
Location of files used for inheritance

### ISSUE THREAD

**Issue by TxHawks** [pattern-lab/patternengine-php-twig#17]
@dmolsen @EvanLovely  -

The README states that files used for template inheritance (i.e., the `extends` tag), must go in `source/_layouts`.

However, in commit [16fe2ba](https://github.com/pattern-lab/starterkit-twig-demo/pull/4/commits/16fe2bab9865a585bad91213ce4e9a44bb437853) of [pattern-lab/patternengine-php-twig](https://github.com/pattern-lab/starterkit-twig-demo), the `01-homepage.twig` template extend
`00-site.twig` from the `_patterns/03-templates` directory, not the `_layouts` directory.

Is this now possible? If so, the README should be changed.

**Comment by EvanLovely** [comment]
I found it possible and was able to use the same pattern lab shorthand syntax as the includes with the extends. Super powerful feature!

**Comment by EvanLovely** [comment]
Perhaps we just need to change must to can. It's an optional spot for templates that don't show in the main pattern library list.

**Comment by aleksip** [comment]
I'm afraid this looks like another case of new undocumented/non-standard features introduced by my Drupal PRs: pattern-lab/patternengine-php-twig#12

Another reason for a `patternengine-php-drupal`?

**Comment by TxHawks** [comment]
I actually think it is an improvement. Especially for embed, it is useful to be able to extend regular patterns, while still retaining the ability have layouts from `_layouts` that aren't presented in the styleguides. It's having the best of both worlds.

**Comment by dmolsen** [comment]
If this was introduced as a needed fix or to make sense to Drupal devs I vote keep it and document it.

**Comment by EvanLovely** [comment]
@dmolsen FYI I've merged in @TxHawks docs pr (#18) and then also made a tweak myself (#19).
