### ISSUE TITLE
Tag embed not working anymore

### ISSUE THREAD

**Issue by schauer** [pattern-lab/patternengine-php-twig#20]
The commit https://github.com/pattern-lab/patternengine-php-twig/commit/b5ed124547944abc7a0d5ad70be2523b60c63934 prevents using the Tag embed.
The Solution is to add another Node Visitor _EmbedNodeVisitor_ which creates an _PatternDataEmbedNode_ exending _Twig_Node_Embed_.
In Addition prevent in the _IncludeNodeVisitor_ creating a _PatternDataIncludeNode_ class in case the $node is an object of _Twig_Node_Embed_.
Something like 
<code>if ($node instanceof \Twig_Node_Include && !($node instanceof \Twig_Node_Embed)) {</code>

**Comment by aleksip** [comment]
Thanks for reporting, will look into it.

**Comment by TxHawks** [comment]
@aleksip -
Is there any way to temporarily work around this? I rely on `embed` pretty heavily.

**Comment by schauer** [comment]
@TxHawks 
Replacing in the file [IncludeNodeVisitor ](https://github.com/pattern-lab/patternengine-php-twig/blob/master/src/PatternLab/PatternEngine/Twig/IncludeNodeVisitor.php#L16 )the line 16 
`if ($node instanceof \Twig_Node_Include) {` with `if ($node instanceof \Twig_Node_Include && !($node instanceof \Twig_Node_Embed)) {`
can be a temporarily solution,

**Comment by aleksip** [comment]
@schauer @TxHawks Working on this right now, hope to have a solution ready today!

**Comment by schauer** [comment]
Thank you, I did not want to rush you.

**Comment by aleksip** [comment]
@schauer @TxHawks Just created a pull request containing a fix for this issue. At least it worked for me. Would be great if you could test it too.

**Comment by schauer** [comment]
@aleksip Looks good to me. I have tested it, and it worked both, include and embed.
Thanks!

**Comment by TxHawks** [comment]
Works here as well

**Comment by aleksip** [comment]
@schauer @TxHawks Thanks for testing!

@dmolsen Thanks for merging!

**Comment by dmolsen** [comment]
`v0.7.1` is now out on Packagist.
