### ISSUE TITLE
Example on how to load extensions?

### ISSUE THREAD

**Issue by iandevlin** [pattern-lab/patternengine-php-twig#27]
Hi,

I notice that there is documentation on how to exend the pattern lab to add your own filters, functions, and tags. But there is also an extensions directory under _twig-components, but there is no example at all on how to load an extension.

Could one be added?

Thanks!

**Comment by dmolsen** [comment]
@iandevlin -

The Twig PatternEngine doesn't look in the directory and load extensions. Sounds like something needs to be cleaned up. I implemented loading the [official Twig Extensions](http://twig.sensiolabs.org/doc/extensions/index.html#extensions-install) as [a Pattern Lab plugin](https://github.com/pattern-lab/plugin-php-twig-extensions/blob/master/src/PatternLab/TwigExtensions/PatternLabListener.php) and maybe that will give you some pointers on how to do this. I realize that's still not documentation but it's the best I can offer at the moment.

It's implemented in a sort of silly way but it works.

**Comment by iandevlin** [comment]
Yeah, I ended up doing something similar in `TwigUtil.php`. I was just wondering if there was some method similar to the others that read the extensions dir and wanted to know what format the file shoud take.
Thanks anyway.
