### ISSUE TITLE
default extension of files in 'source/_twig-components'

### ISSUE THREAD

**Issue by TxHawks** [pattern-lab/patternengine-php-twig#3]
It's not a big deal since it configurable, but since the files under `source/_twig-components`, which are meant to extend Twig itself, aren't actually Twig partials, but rather plain-ol' PHP files, I think a better naming default would be `.[extension-type].php`. 

I think it's clearer and better for syntax highlighting.

**Comment by dmolsen** [comment]
Good call. I've made this switch in `v0.6.1`.
