### ISSUE TITLE
Support for the Twig Extensions Library

### ISSUE THREAD

**Issue by nmeirik** [pattern-lab/patternengine-php-twig#8]
It would be great if the PatternEngine could support the [Twig Extensions Library](http://twig.sensiolabs.org/doc/extensions/index.html#extensions-install) by default.

**Comment by dmolsen** [comment]
Noted and will make it happen. Thanks.

**Comment by dmolsen** [comment]
Probably not needed anymore but I [created a plugin for this](https://github.com/pattern-lab/plugin-php-twig-extensions).
