### ISSUE TITLE
Consider turning off escaping strategy

### ISSUE THREAD

**Issue by nmeirik** [pattern-lab/patternengine-php-twig#9]
By default, Twig has the [escaping strategy](http://twig.sensiolabs.org/doc/api.html#escaper-extension) set to `html`, meaning that HTML tags are automatically escaped. Does this escaping strategy make sense in the context of Pattern Lab? I would argue that as a developer, I should be able to put whatever I want into my `data.json` file (including HTML) without having to explicitly escape it. Hence, it makes sense to me to disable the escaping strategy alltogether.

**Comment by dmolsen** [comment]
I might need to make this a config option but added to the list. Should be straightforward.

For me:
http://stackoverflow.com/questions/13990249/disable-html-escaping-when-manually-rendering-a-twig-string

**Comment by aleksip** [comment]
I believe this issue can now be closed.

**Comment by mathieuhelie** [comment]
This needs better documentation. I had to fiddle with different values and configuration paths deduced from the pull request before I landed on the correct `twigAutoescape: false` in config.yml.

**Comment by EvanLovely** [comment]
@dmolsen I've noticed when I spin up PLs I get a `config.yml` with none of the helpful, documenting comments found in core. I think it's when I have a config that gets updated or something similar, I can get a reproducible scenario for you in a different issue if you'd like.

**Comment by dmolsen** [comment]
@EvanLovely -

Expected behavior. Kicking out a new YAML file when an option is changed will destroy all comments. Unfortunate but no real good way around it that I'm aware of. Not that I've researched it extensively.

**Comment by dmolsen** [comment]
@mathieuhelie -

Thanks for the heads up. I'll try to get that documented properly in the README.
